version: '3'

services:

  cassandra-1:
    image: cassandra:4.0.7
    restart: always
    volumes: # TODO: Create directory on your machine
      - "/c/docker/cassandra1:/var/lib/cassandra"
    ports: # TODO: Set other port on the left if it's already used on your machine
      - "9042:9042"
    container_name: cassandra-1
    networks:
      - cassandra_network

  cassandra-2:
    image: cassandra:4.0.7
    restart: always
    volumes: # TODO: Create directory on your machine
      - "/c/docker/cassandra2:/var/lib/cassandra"
    ports: # TODO: Set other port on the left if it's already used on your machine
      - "9043:9042"
    environment:
      - CASSANDRA_SEEDS=cassandra-1
    container_name: cassandra-2
    networks:
      - cassandra_network

  cassandra-3:
    image: cassandra:4.0.7
    restart: always
    volumes: # TODO: Create directory on your machine
      - "/c/docker/cassandra3:/var/lib/cassandra"
    ports: # TODO: Set other port on the left if it's already used on your machine
      - "9044:9042"
    environment:
      - CASSANDRA_SEEDS=cassandra-1
    container_name: cassandra-3
    networks:
      - cassandra_network

# TODO: docker network create cassandra_network --driver bridge
networks:
  cassandra_network: