version: '3'

services:

  spark:
    image: bitnami/spark:3.2.2
    user: root
    restart: always
    depends_on: # TODO: Add databases
      - postgres
      - cassandra
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports: # TODO: Set other port on the left if it's already used on your machine
      - "8081:8080" # TODO: We use non standard port 8081 since 8080 already used by Trino
    container_name: spark
    networks:
      - spark_network

  spark-worker:
    image: bitnami/spark:3.2.2
    user: root
    restart: always
    depends_on: # TODO Add databases
      - postgres
      - cassandra
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    container_name: spark-worker
    networks:
      - spark_network

  spark-thrift:
    image: bitnami/spark:3.2.2 #  TODO: Build custom image from Dockerfile
    #image: 728f339af4a3
    user: root
    restart: always
    depends_on:
      - spark
    environment:
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "10000:10000"
    container_name: spark-thrift
    networks:
      - spark_network

networks:
  spark_network: