version: '3'

# https://stackoverflow.com/questions/70081871/minio-cluster-on-different-hosts-by-docker

services:

  minio1: # rename on different nodes
    restart: always
    image: 'bitnami/minio:latest'
    container_name: minio1 # rename on different nodes
    hostname: minio1 # rename on different nodes
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio1,minio2,minio3,minio4 # TODO:
      - MINIO_SKIP_CLIENT=yes
    extra_hosts: # TODO:
      - "minio1:192.168.0.1"  # 1st node
      - "minio2:192.168.0.2"  # 2nd node
      - "minio3:192.168.0.3"  # 3rd node
      - "minio4:192.168.0.4"  # 4th node
    volumes:
      - /opt/docker/minio/data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3