version: '3'

# https://stackoverflow.com/questions/70081871/minio-cluster-on-different-hosts-by-docker

services:

  minio1: # rename on different nodes
    image: 'bitnami/minio:latest'
    restart: always
    hostname: minio1            # rename on different nodes
    command: server --console-address ":9001" http://minio{1...4}/data{1...2}
    ports:
      - "3000:9000"
      - "3001:9001"
    extra_hosts:
      - "minio1:192.168.0.1"  # 1st node
      - "minio2:192.168.0.2"  # 2nd node
      - "minio3:192.168.0.3"  # 3rd node
      - "minio3:192.168.0.4"  # 4th node
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - data1-1:/data1          # rename on different nodes
      - data1-2:/data2          # rename on different nodes
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  data1-1:                      # rename on different nodes
  data1-2:                      # rename on different nodes